spring.application.name=teste

#ver as tabelas no navegador em localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#configuração da conexão (banco de memória)
spring.datasource.url=jdbc:h2:mem:clinicadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.settings.web-allow-others=true
server.error.include-message=always

#JPA / Hibernate: mostra o SQL no console e cria as tabelas sozinho
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect